### PR TITLE
fixed setup.py so that it actualy installs the module mcp3008

### PR DESCRIPTION
**Pull request by AndySchroder**

### CODE REVIEW

**Comment by luxedo** [comment]
This is the very first package I published, thank you!
I'll try to create a new release right now

**Comment by luxedo** [comment]
The new version [1.0.1](https://pypi.org/project/mcp3008/1.0.1/) is up!

**Comment by AndySchroder** [comment]
When does it make it to pypi?

**Comment by luxedo** [comment]
It's already up! Just install it again or upgrade it:
```bash
pip install mcp3008==1.0.1
# or
pip install -U mcp3008
```

**Pull request merged**
